// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:1918db0d-482e-4da3-9d6d-f2a09b01eb93",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_GEjkJTFdi",
    "aws_user_pools_web_client_id": "7ppfog2chn8eoj7lr6ecc17t4h",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://s3a6c37osba7bmaaxadd4jvlza.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
